# 作業 : (Kaggle)鐵達尼生存預測精簡版 
https://www.kaggle.com/c/titanic

# [作業目標]
- 試著不依賴說明, 只依照下列程式碼回答下列問題, 初步理解什麼是"特徵工程"的區塊

# [作業重點]
- 試著不依賴註解, 以之前所學, 回答下列問題

# 作業1
* 下列A~E五個程式區塊中，哪一塊是特徵工程?
*  ans: C

# 作業2
* 對照程式區塊 B 與 C 的結果，請問那些欄位屬於"類別型欄位"? (回答欄位英文名稱即可) 
*  ans: Name,Sex,Ticket,Cabin,Embarked

# 作業3
* 續上題，請問哪個欄位是"目標值"?
*  ans: pred,train_Y

In [1]:
# 程式區塊 A
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

data_path = 'data/'
df_train = pd.read_csv(data_path + 'titanic_train.csv')
df_test = pd.read_csv(data_path + 'titanic_test.csv')
df_train.shape
df_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [2]:
# 程式區塊 B
train_Y = df_train['Survived']
ids = df_test['PassengerId']
df_train = df_train.drop(['PassengerId', 'Survived'] , axis=1)
df_test = df_test.drop(['PassengerId'] , axis=1)
df = pd.concat([df_train,df_test])
df.head(30)

Pclass                                               Name     Sex   Age  \
0        3                            Braund, Mr. Owen Harris    male  22.0   
1        1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
2        3                             Heikkinen, Miss. Laina  female  26.0   
3        1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
4        3                           Allen, Mr. William Henry    male  35.0   
5        3                                   Moran, Mr. James    male   NaN   
6        1                            McCarthy, Mr. Timothy J    male  54.0   
7        3                     Palsson, Master. Gosta Leonard    male   2.0   
8        3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0   
9        2                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0   
10       3                    Sandstrom, Miss. Marguerite Rut  female   4.0   
11       1                           Bonnell, Miss. Elizabeth  female  58.0   
12       3                     Saundercock, Mr. William Henry    male  20.0   
13       3                        Andersson, Mr. Anders Johan    male  39.0   
14       3               Vestrom, Miss. Hulda Amanda Adolfina  female  14.0   
15       2                   Hewlett, Mrs. (Mary D Kingcome)   female  55.0   
16       3                               Rice, Master. Eugene    male   2.0   
17       2                       Williams, Mr. Charles Eugene    male   NaN   
18       3  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0   
19       3                            Masselmani, Mrs. Fatima  female   NaN   
20       2                               Fynney, Mr. Joseph J    male  35.0   
21       2                              Beesley, Mr. Lawrence    male  34.0   
22       3                        McGowan, Miss. Anna "Annie"  female  15.0   
23       1                       Sloper, Mr. William Thompson    male  28.0   
24       3                      Palsson, Miss. Torborg Danira  female   8.0   
25       3  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female  38.0   
26       3                            Emir, Mr. Farred Chehab    male   NaN   
27       1                     Fortune, Mr. Charles Alexander    male  19.0   
28       3                      O'Dwyer, Miss. Ellen "Nellie"  female   NaN   
29       3                                Todoroff, Mr. Lalio    male   NaN   

    SibSp  Parch            Ticket      Fare        Cabin Embarked  
0       1      0         A/5 21171    7.2500          NaN        S  
1       1      0          PC 17599   71.2833          C85        C  
2       0      0  STON/O2. 3101282    7.9250          NaN        S  
3       1      0            113803   53.1000         C123        S  
4       0      0            373450    8.0500          NaN        S  
5       0      0            330877    8.4583          NaN        Q  
6       0      0             17463   51.8625          E46        S  
7       3      1            349909   21.0750          NaN        S  
8       0      2            347742   11.1333          NaN        S  
9       1      0            237736   30.0708          NaN        C  
10      1      1           PP 9549   16.7000           G6        S  
11      0      0            113783   26.5500         C103        S  
12      0      0         A/5. 2151    8.0500          NaN        S  
13      1      5            347082   31.2750          NaN        S  
14      0      0            350406    7.8542          NaN        S  
15      0      0            248706   16.0000          NaN        S  
16      4      1            382652   29.1250          NaN        Q  
17      0      0            244373   13.0000          NaN        S  
18      1      0            345763   18.0000          NaN        S  
19      0      0              2649    7.2250          NaN        C  
20      0      0            239865   26.0000          NaN        S  
21      0      0            248698  

In [3]:
# 程式區塊 C
LEncoder = LabelEncoder()
MMEncoder = MinMaxScaler()
for c in df.columns:
    print(df[c].dtype)
    df[c] = df[c].fillna(-1)
    print(df[c].head())
    if df[c].dtype == 'object':
        print("12345678")
        df[c] = LEncoder.fit_transform(list(df[c].values))
        
    print(df[c].values) 
    df[c] = MMEncoder.fit_transform(df[c].values.reshape(-1, 1))

int64
0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64
[3 1 3 ... 3 3 3]
object
0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: object
12345678
[ 155  286  523 ... 1046 1227  953]
object
0      male
1    female
2    female
3    female
4      male
Name: Sex, dtype: object
12345678
[1 0 0 ... 1 1 1]
float64
0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: Age, dtype: float64
[22.  38.  26.  ... 38.5 -1.  -1. ]
int64
0    1
1    1
2    0
3    1
4    0
Name: SibSp, dtype: int64
[1 1 0 ... 0 0 1]
int64
0    0
1    0
2    0
3    0
4    0
Name: Parch, dtype: int64
[0 0 0 ... 0 0 1]
object
0           A/5 21171
1            PC 17599
2    STON/O2. 3101282
3              113803
4              373450
Name: Ticket, dtype: object
1234567

C:\Users\Pheobe\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Pheobe\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Pheobe\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Pheobe\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Pheobe\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to

In [4]:
df.head(30)

Pclass      Name  Sex       Age  SibSp     Parch    Ticket      Fare  \
0      1.0  0.118683  1.0  0.283951  0.125  0.000000  0.775862  0.016072   
1      0.0  0.218989  0.0  0.481481  0.125  0.000000  0.879310  0.140813   
2      1.0  0.400459  0.0  0.333333  0.000  0.000000  0.984914  0.017387   
3      0.0  0.323124  0.0  0.444444  0.125  0.000000  0.070043  0.105390   
4      1.0  0.016845  1.0  0.444444  0.000  0.000000  0.699353  0.017630   
5      1.0  0.626340  1.0  0.000000  0.000  0.000000  0.401940  0.018425   
6      0.0  0.587289  1.0  0.679012  0.000  0.000000  0.117457  0.102980   
7      1.0  0.699847  1.0  0.037037  0.375  0.111111  0.582974  0.043004   
8      1.0  0.463247  0.0  0.345679  0.000  0.222222  0.514009  0.023636   
9      0.5  0.648545  0.0  0.185185  0.125  0.000000  0.187500  0.060528   
10     1.0  0.816998  0.0  0.061728  0.125  0.111111  0.904095  0.034481   
11     0.0  0.101838  0.0  0.728395  0.000  0.000000  0.053879  0.053669   
12     1.0  0.819296  1.0  0.259259  0.000  0.000000  0.789871  0.017630   
13     1.0  0.029096  1.0  0.493827  0.125  0.555556  0.494612  0.062874   
14     1.0  0.934916  0.0  0.185185  0.000  0.000000  0.609914  0.017249   
15     0.5  0.408116  0.0  0.691358  0.000  0.000000  0.219828  0.033117   
16     1.0  0.761868  1.0  0.037037  0.500  0.111111  0.710129  0.058686   
17     0.5  0.973201  1.0  0.000000  0.000  0.000000  0.216595  0.027273   
18     1.0  0.931853  0.0  0.395062  0.125  0.000000  0.449353  0.037013   
19     1.0  0.581930  0.0  0.000000  0.000  0.000000  0.261853  0.016023   
20     0.5  0.323890  1.0  0.444444  0.000  0.000000  0.196121  0.052598   
21     0.5  0.085758  1.0  0.432099  0.000  0.000000  0.218750  0.027273   
22     1.0  0.595712  0.0  0.197531  0.000  0.000000  0.408405  0.017589   
23     0.0  0.850689  1.0  0.358025  0.000  0.000000  0.058190  0.071104   
24     1.0  0.702144  0.0  0.111111  0.375  0.111111  0.582974  0.043004   
25     1.0  0.049005  0.0  0.481481  0.125  0.555556  0.489224  0.063093   
26     1.0  0.284074  1.0  0.000000  0.000  0.000000  0.256466  0.016023   
27     0.0  0.309342  1.0  0.246914  0.375  0.222222  0.132543  0.514290   
28     1.0  0.677642  0.0  0.000000  0.000  0.000000  0.414871  0.017297   
29     1.0  0.908116  1.0  0.000000  0.000  0.000000  0.537716  0.017330   

       Cabin  Embarked  
0   0.000000  1.000000  
1   0.575269  0.333333  
2   0.000000  1.000000  
3   0.381720  1.000000  
4   0.000000  1.000000  
5   0.000000  0.666667  
6   0.881720  1.000000  
7   0.000000  1.000000  
8   0.000000  1.000000  
9   0.000000  0.333333  
10  0.994624  1.000000  
11  0.338710  1.000000  
12  0.000000  1.000000  
13  0.000000  1.000000  
14  0.000000  1.000000  
15  0.000000  1.000000  
16  0.000000  0.666667  
17  0.000000  1.000000  
18  0.000000  1.000000  
19  0.000000  0.333333  
20  0.000000  1.000000  
21  0.774194  1.000000  
22  0.000000  0.666667  
23  0.096774  1.000000  
24  0.000000  1.000000  
25  0.000000  1.000000  
26  0.000000  0.333333  
27  0.435484  1.000000  
28  0.000000  0.666667  
29  0.000000  1.000000

In [5]:
# 程式區塊 D
train_num = train_Y.shape[0]
train_X = df[:train_num]
test_X = df[train_num:]

from sklearn.linear_model import LogisticRegression
estimator = LogisticRegression()
estimator.fit(train_X, train_Y)
pred = estimator.predict(test_X)

C:\Users\Pheobe\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [6]:
# 程式區塊 E
sub = pd.DataFrame({'PassengerId': ids, 'Survived': pred})
sub.to_csv('titanic_baseline.csv', index=False) 